---
- hosts: local
  connection: local
  tasks:
  - name: Playbook 2 - Update the repository cache and update package "nginx" to latest version using default release squeeze-backport
    apt:
      name: nginx
      state: latest
      update_cache: yes
    become: true

  - name: make sure nginx is running
    service: 
      name: nginx 
      state: started
    become: true

  - name: Installation de git
    apt:
      name: git
      state: latest
      update_cache: yes
    become: true

  - name: Installation de git-mc-vim-curl
    apt:
      name: "{{ item }}"
    with_items:
      - git
      - mc
      - vim
      - apt-transport-https
      - ca-certificates
      - curl
    become: true

#   sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
# sudo apt-get update
# sudo apt-get install ansible   
# Add an apt key by id from a keyserver
  - apt_key:
      keyserver: keyserver.ubuntu.com
      id: 93C4A3FD7BB9C367

  - name: Installation d'ansible
    apt:
      name: ansible
      state: latest
    become: true
  
#  - name: Installation de MC
#    apt:
#      name: mc
#      become: true

...